apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /srv/www
          name: pv-storage
      - name: nodeserver
        image: fafiso/userapi_project_devops:latest
        ports:
        - containerPort: 8080
      
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pv-claim
